In [ ]:
print("Hlo")

Hlo


In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,60])
a1 = np.array([1,2,3,4,5,6])

a + a1

array([ 2,  4,  6,  8, 10, 66])

In [16]:
num = np.arange(1,31).reshape(6,5)
num

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [27]:
num[4,4]

np.int64(25)

In [30]:
slice = num[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [32]:
slice2 = num[3:6, 3:5]
slice2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [34]:
col3 = num[:,3]
col3

array([ 4,  9, 14, 19, 24, 29])

**Boolean Indexing**

In [36]:
arr = np.arange(11,32)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31])

In [38]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])